version: '3'

env:
  PROJECT_NAME: pet-store

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']


tasks:
  default:
    cmds:
        - echo "Project $PROJECT_NAME"
        - task --list-all
    silent: true

  build:
    desc: Собирает исполняемый файл приложения
    deps:
      - install-deps
    cmds:
      - go build -v -o ./bin/$PROJECT_NAME.exe cmd/$PROJECT_NAME/main.go

  docker-run:
    desc: Запускает исполняемый файл приложения
    cmds:
      - ./bin/$PROJECT_NAME.exe

  run:
    desc:  Запускает исполняемый файл приложения
    cmds:
      - go run ./cmd/$PROJECT_NAME/main.go

  lint:
    desc: Запускает проверку кода
    deps:
      - install-deps
    cmds:
      - golangci-lint run --fix

  install-deps:
    desc: Установка всех необходимых зависимости проекта
    cmds:
      # - pre-commit install
      # - pre-commit install --hook-type commit-msg
      - go mod download
      # - docker compose up -d

  create-migration:
    desc: Создает новую миграцию
    dir: migrations
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - goose -s create new_migration sql

  run-migrations:
    desc: Запускает миграцию
    dir: migrations
    cmds:
      - goose postgres "postgres://postgres:postgres@localhost:5432/postgres" up
