@startuml create

'Шаблон
!theme materia-outline
autonumber
skinparam responseMessageBelowArrow true
skinparam sequenceMessageAlign center
skinparam sequenceArrowThickness 2
!pragma teoz true

'Участники процесса
participant "admin"   as Admin
participant "pet-store"   as Service
database    "База данных"       as DB

'Действия

Admin -> Service: Регистрирует питомца
Service -> Service: Создадим сущность питомца в системе
Service -> Service: Задать статус питомцу "ON_MEDICAL_EXAMINATION"
Service -> DB: Сохранить в БД
Service -> Admin: $success("питомец успешно добавлен")


@enduml
