// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/mai/pet-store/v1/service/contracts/pet_update.proto

package contracts

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpdatePetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdatePetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdatePetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdatePetRequestMultiError, or nil if none found.
func (m *UpdatePetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdatePetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return UpdatePetRequestMultiError(errors)
	}

	return nil
}

// UpdatePetRequestMultiError is an error wrapping multiple validation errors
// returned by UpdatePetRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdatePetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdatePetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdatePetRequestMultiError) AllErrors() []error { return m }

// UpdatePetRequestValidationError is the validation error returned by
// UpdatePetRequest.Validate if the designated constraints aren't met.
type UpdatePetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePetRequestValidationError) ErrorName() string { return "UpdatePetRequestValidationError" }

// Error satisfies the builtin error interface
func (e UpdatePetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePetRequestValidationError{}

// Validate checks the field values on UpdatePetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdatePetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdatePetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdatePetResponseMultiError, or nil if none found.
func (m *UpdatePetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdatePetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdatePetResponseMultiError(errors)
	}

	return nil
}

// UpdatePetResponseMultiError is an error wrapping multiple validation errors
// returned by UpdatePetResponse.ValidateAll() if the designated constraints
// aren't met.
type UpdatePetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdatePetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdatePetResponseMultiError) AllErrors() []error { return m }

// UpdatePetResponseValidationError is the validation error returned by
// UpdatePetResponse.Validate if the designated constraints aren't met.
type UpdatePetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePetResponseValidationError) ErrorName() string {
	return "UpdatePetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePetResponseValidationError{}
