// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/mai/pet-store/v1/service/contracts/pet_create.proto

package contracts

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreatePetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreatePetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePetRequestMultiError, or nil if none found.
func (m *CreatePetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return CreatePetRequestMultiError(errors)
	}

	return nil
}

// CreatePetRequestMultiError is an error wrapping multiple validation errors
// returned by CreatePetRequest.ValidateAll() if the designated constraints
// aren't met.
type CreatePetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePetRequestMultiError) AllErrors() []error { return m }

// CreatePetRequestValidationError is the validation error returned by
// CreatePetRequest.Validate if the designated constraints aren't met.
type CreatePetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePetRequestValidationError) ErrorName() string { return "CreatePetRequestValidationError" }

// Error satisfies the builtin error interface
func (e CreatePetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePetRequestValidationError{}

// Validate checks the field values on CreatePetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreatePetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePetResponseMultiError, or nil if none found.
func (m *CreatePetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreatePetResponseMultiError(errors)
	}

	return nil
}

// CreatePetResponseMultiError is an error wrapping multiple validation errors
// returned by CreatePetResponse.ValidateAll() if the designated constraints
// aren't met.
type CreatePetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePetResponseMultiError) AllErrors() []error { return m }

// CreatePetResponseValidationError is the validation error returned by
// CreatePetResponse.Validate if the designated constraints aren't met.
type CreatePetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePetResponseValidationError) ErrorName() string {
	return "CreatePetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePetResponseValidationError{}
