// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/mai/pet-store/v1/service/contracts/pet_search.proto

package contracts

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearchPetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SearchPetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchPetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchPetRequestMultiError, or nil if none found.
func (m *SearchPetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchPetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return SearchPetRequestMultiError(errors)
	}

	return nil
}

// SearchPetRequestMultiError is an error wrapping multiple validation errors
// returned by SearchPetRequest.ValidateAll() if the designated constraints
// aren't met.
type SearchPetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchPetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchPetRequestMultiError) AllErrors() []error { return m }

// SearchPetRequestValidationError is the validation error returned by
// SearchPetRequest.Validate if the designated constraints aren't met.
type SearchPetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchPetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchPetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchPetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchPetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchPetRequestValidationError) ErrorName() string { return "SearchPetRequestValidationError" }

// Error satisfies the builtin error interface
func (e SearchPetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchPetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchPetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchPetRequestValidationError{}

// Validate checks the field values on SearchPetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SearchPetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchPetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchPetResponseMultiError, or nil if none found.
func (m *SearchPetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchPetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SearchPetResponseValidationError{
						field:  fmt.Sprintf("Pets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SearchPetResponseValidationError{
						field:  fmt.Sprintf("Pets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SearchPetResponseValidationError{
					field:  fmt.Sprintf("Pets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SearchPetResponseMultiError(errors)
	}

	return nil
}

// SearchPetResponseMultiError is an error wrapping multiple validation errors
// returned by SearchPetResponse.ValidateAll() if the designated constraints
// aren't met.
type SearchPetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchPetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchPetResponseMultiError) AllErrors() []error { return m }

// SearchPetResponseValidationError is the validation error returned by
// SearchPetResponse.Validate if the designated constraints aren't met.
type SearchPetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchPetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchPetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchPetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchPetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchPetResponseValidationError) ErrorName() string {
	return "SearchPetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchPetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchPetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchPetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchPetResponseValidationError{}
