// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/mai/pet-store/v1/service/contracts/pet_get.proto

package contracts

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetPetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetPetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetPetRequestMultiError, or
// nil if none found.
func (m *GetPetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetPetRequestMultiError(errors)
	}

	return nil
}

// GetPetRequestMultiError is an error wrapping multiple validation errors
// returned by GetPetRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPetRequestMultiError) AllErrors() []error { return m }

// GetPetRequestValidationError is the validation error returned by
// GetPetRequest.Validate if the designated constraints aren't met.
type GetPetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPetRequestValidationError) ErrorName() string { return "GetPetRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetPetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPetRequestValidationError{}

// Validate checks the field values on GetPetResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetPetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetPetResponseMultiError,
// or nil if none found.
func (m *GetPetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPet()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetPetResponseValidationError{
					field:  "Pet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetPetResponseValidationError{
					field:  "Pet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPetResponseValidationError{
				field:  "Pet",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetPetResponseMultiError(errors)
	}

	return nil
}

// GetPetResponseMultiError is an error wrapping multiple validation errors
// returned by GetPetResponse.ValidateAll() if the designated constraints
// aren't met.
type GetPetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPetResponseMultiError) AllErrors() []error { return m }

// GetPetResponseValidationError is the validation error returned by
// GetPetResponse.Validate if the designated constraints aren't met.
type GetPetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPetResponseValidationError) ErrorName() string { return "GetPetResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetPetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPetResponseValidationError{}
